### ISSUE TITLE
Elasticsearch Search function doesn't provide all the necessary results

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/benchmark-comparison#35]
With kube-burner there are thousands of documents. By default search will only return 10... We should use `scroll`

**Comment by amitsagtani97** [comment]
@jtaleric we can close this issue, as this is fixed here - https://github.com/cloud-bulldozer/benchmark-comparison/blob/master/src/touchstone/databases/elasticsearch.py#L82
