### ISSUE TITLE
How the comparison deal with the date in the ES data?

### ISSUE THREAD

**Issue by inevity** [cloud-bulldozer/benchmark-comparison#52]
Same as Title

**Comment by rsevilla87** [comment]
Hi, not sure what you mean with your question, I'll try to answer it with some comments:
Benchmark-comparison is able to output metric aggregations such as avg, max P99 from a given set of documents with the same id (uuid by default).
We recently have added the feature of querying and outputing raw data, documented at https://github.com/cloud-bulldozer/benchmark-comparison#querying-for-raw-data, by using that feature you can get a whole series of documents in different formats.

**Comment by inevity** [comment]
For example, we have two uuid data, such as es time date ingest by the snafu wrapper.  
we just metric aggregations such as avg, max P99. I now understand this.
Should we need the two uuid data should be same time duration, or should have same amount of the data point to compare?

**Comment by rsevilla87** [comment]
> For example, we have two uuid data, such as es time date ingest by the snafu wrapper.
> we just metric aggregations such as avg, max P99. I now understand this.
> Should we need the two uuid data should be same time duration, or should have same amount of the data point to compare?

Hey @inevity, they don't need to be 100% similar, those documents just need to have the fields in common you use for buckets and/on filters. i.e, find more examples in the config dir. https://github.com/cloud-bulldozer/benchmark-comparison/tree/master/config
